# Generated by Django 6.0.2 on 2026-02-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_question_matchpair_choice_quiz_question_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='show_correct_answers',
            field=models.BooleanField(default=True, verbose_name='Показывать правильные ответы после прохождения'),
        ),
    ]
