# Generated by Django 6.0.2 on 2026-03-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_quiz_show_correct_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='courses/avatars/'),
        ),
        migrations.AddField(
            model_name='course',
            name='avatar_color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
