# Generated by Django 6.0.2 on 2026-03-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_category_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('programming', 'Программирование'), ('math', 'Математика'), ('design', 'Дизайн')], max_length=50, null=True, verbose_name='Категория'),
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
