# Generated by Django 6.0.2 on 2026-03-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_category_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('algebra', 'Алгебра'), ('geometry', 'Геометрия'), ('uiux', 'UI/UX'), ('graphic', 'Графический дизайн')], max_length=50, null=True, verbose_name='Подкатегория'),
        ),
    ]
