# Generated by Django 6.0.2 on 2026-04-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Открыт с'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='Сдано после дедлайна'),
        ),
    ]
