# Generated by Django 6.0.2 on 2026-05-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_is_private_course_access_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('programming', 'Программирование'), ('math', 'Высшая математика'), ('design', 'Дизайн'), ('school_program', 'Школьная программа'), ('foreign_lang', 'Иностранные языки')], max_length=50, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('go', 'Go'), ('c', 'C'), ('c_sharp', 'C#'), ('java_script', 'JavaScript'), ('web', 'Web-разработка'), ('html', 'HTML'), ('css', 'CSS'), ('front', 'Frontend-разработка'), ('lin_algebra', 'Линейная алгебра'), ('discr_math', 'Дискретная математика'), ('math_analys', 'Математический анализ'), ('diff_uravn', 'Дифференциальные уравнения'), ('chisl_methods', 'Численные методы'), ('uravn_math_physics', 'Уравнения математической физики'), ('uiux', 'UI/UX'), ('graphic', 'Графический дизайн'), ('s_math', 'Математика'), ('s_foreign_lang', 'Иностранный язык'), ('s_programming', 'Информатика'), ('s_biology', 'Биология'), ('s_russian', 'Русский язык'), ('s_geography', 'География'), ('s_economy', 'Экономика'), ('s_history', 'История'), ('s_social_science', 'Обществознание'), ('s_physics', 'Физика'), ('english', 'Английский язык'), ('german', 'Немецкий язык'), ('french', 'Французский язык'), ('spanish', 'Испанский язык')], max_length=50, null=True, verbose_name='Подкатегория'),
        ),
    ]
